services:
  - type: web
    name: skv-tender-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10.13
    plan: free
    autoDeploy: true
    pythonVersion: 3.10.13
